# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"nvim" = "îŸ…"
"alacritty" = "ï„ "
"kitty" = "ï„ "
"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"private browsing" = "ïˆ›"
"brave" = "ïª"
"file manager" = "ï¼"
"thunar" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"office" = "ï£…"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ïœª"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ïœ¤"
"firefox" = "ï‰©"
"designer" = "ï§¯"
"apache" = "ï¤…"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
